### ISSUE TITLE
置いた場所が空きマスなのかの判定はget_flip_count外でやりたい

### ISSUE THREAD

**Issue by yuta0428** [WROS-eng/netpro#7]
### 概要
- 置いた際に空きマスではなかったのかひっくり返す石が無かったのか分かりづらい
- なので、打つ→空きマス判定→空きマスなら`get_flip_count`としたい

### コード
https://github.com/WROS-eng/netpro/blob/4730a9e695aaf71eace54d72b311b50254afff3a/client_board.rb#L49-L51

**Comment by shoka-ochi** [comment]
追加したンゴ！
